# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master
- v*

steps:
- script: GIT_BRANCH=$(build.SourceBranchName) make docker_build
  displayName: 'Build kubectl container'
- script: GIT_BRANCH=$(build.SourceBranchName) make test
  displayName: 'Test kubectl container'
- script: |
    docker login -u $(dockerId) -p $(pswd)
    GIT_BRANCH=$(build.SourceBranchName) make docker_push
  condition: or(startsWith(variables['Build.SourceBranchName'], 'v'), startsWith(variables['Build.SourceBranchName'], 'master'))
  displayName: 'Publish kubectl container'

